{% set name = "jupyterlab_server" %}
{% set version = "2.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4f5b48eaae1be83e2fd6fb77ac49d9b639be4ca4bd2e05b5368d29632a93725

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - hatchling 1.8
    - setuptools
    - wheel
  run:
    - python
    - babel >=2.10
    - importlib-metadata >=4.8.3  # [py<310]
    - jinja2 >=3.0.3
    - json5 >=0.9.0
    - jsonschema >=4.17.3
    - jupyter_server >=1.21,<3
    - packaging >=21.3
    - requests >=2.28

test:
  requires:
    - pip
  imports:
    - jupyterlab_server
  commands:
    - pip check
    - python -m pip check 
  # downstreams:
    # Additional testing for downstream package jupyterlab
    # 1. Skip s390x and arm64 because nodejs >=14,<15 currently isn't available.
    # 2. Skip ppc64le: npm dependencies failed to install
    #- jupyterlab  # [not (s390x or aarch64 or arm64 or ppc64le)]

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  description: |
    JupyterLab Server sits between JupyterLab and Jupyter Server, and provides a set of REST API handlers 
    and utilities that are used by JupyterLab. It is a separate project in order to accommodate creating 
    JupyterLab-like applications from a more limited scope.
  dev_url: https://github.com/jupyterlab/jupyterlab_server
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
