{% set name = "jupyterlab_server" %}
{% set version = "2.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35baa81898b15f93573e2deca50d11ac0ae407ebb688299d3a5213265033712c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.7
  run:
    - python
    - babel >=2.10
    - importlib-metadata >=4.8.3  # [py<310]
    - jinja2 >=3.0.3
    - json5 >=0.9.0
    - jsonschema >=4.18.0
    - jupyter_server >=1.21,<3
    - packaging >=21.3
    - requests >=2.31
  run_constrained:
    - openapi-core >=0.18.0,<0.19.0

# E   ModuleNotFoundError: No module named 'openapi_core'
{% set ignore_tests = " --ignore=tests/test_translation_api.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_themes_api.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_labapp.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_settings_api.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_workspaces_api.py" %}
# E   ModuleNotFoundError: No module named 'requests_mock'
{% set ignore_tests = ignore_tests + " --ignore=tests/test_listings_api.py" %}
test:
  source_files:
    - tests
  imports:
    - jupyterlab_server
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }}
  requires:
    - pip
    - pytest >=7
    - pytest-jupyter >=0.6.2
    - mock
    - strict-rfc3339
  # downstreams:
  #   # Additional testing for downstream packages
  #   - jupyterlab 4.4.7
  #   - notebook 7.4.5
  #   - voila 0.5.8

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  description: |
    JupyterLab Server sits between JupyterLab and Jupyter Server, and provides a
    set of REST API handlers and utilities that are used by JupyterLab. It is a
    separate project in order to accommodate creating JupyterLab-like
    applications from a more limited scope.
  dev_url: https://github.com/jupyterlab/jupyterlab_server
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  skip-lints:
    # `packaging` is required, noted as a dependency by upstream:
    # https://github.com/jupyterlab/jupyterlab_server/blob/v2.28.0/pyproject.toml#L36
    # It is worth noting that the project still builds without it.
    - python_build_tool_in_run
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
