{% set version = "2.15.2" %}
{% set hash = "c0bcdd4606e640e6f16d236ceac55336dc8bf98cbbce067af27524ccc2fb2640" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - hatchling >=0.25
  run:
    - python
    - babel
    - importlib-metadata >=3.6  # [py<310]
    - jinja2 >=3.0.3
    - json5
    - jsonschema >=3.0.1
    - jupyter_server >=1.8,<2
    - packaging
    - requests

test:
  requires:
    - pip
  imports:
    - jupyterlab_server
  commands:
    # Skip win: false positive jupyter-server 1.13.5 has requirement pywinpty<2 but you have pywinpty 2.0.2.
    - python -m pip check  # [not win]
#  downstreams:
    # Additional testing for downstream package jupyterlab
    # 1. Skip s390x and arm64 because nodejs >=14,<15 currently isn't available.
    # 2. Skip ppc64le: npm dependencies failed to install
#    - jupyterlab  # [not (s390x or aarch64 or arm64 or ppc64le)]

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  dev_url: https://github.com/jupyterlab/jupyterlab_server
  doc_url: https://jupyterlab-server.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
