{% set version = "2.10.2" %}
{% set hash = "bf1ec9e49d4e26f14d70055cc293b3f8ec8410f95a4d5b4bd55c442d9b8b266c" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - jupyter-packaging >=0.9,<2
    - jupyter_server
    - setuptools
    - wheel
  run:
    - python >=3.6
    - babel
    - entrypoints >=0.2.2
    - json5
    - jsonschema >=3.0.1
    - jinja2 >=2.10
    - jupyter_server >=1.4,<2
    - packaging
    - requests

test:
  requires:
    - pip
    - python <3.10
  imports:
    - jupyterlab_server
  commands:
    - python -m pip check

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  dev_url: https://github.com/jupyterlab/jupyterlab_server
  doc_url: https://jupyterlab-server.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
