{% set version = "0.3.1" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: 2f2e6fadb0fcaed8305e29389ca8f9bd00c41ba0f7351c85673e227d1dd6fa2c

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - notebook

test:
  imports:
    - jupyterlab_server

about:
  home: http://github.com/jupyterlab/jupyterlab_server
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
