{% set version = "0.3.4" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: ae0c8629b9f0196b314f017e374a70a702522739f4f08bece84963af5e8c8351

build:
    number: 0
    skip: True  # [py<35]
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - notebook

test:
  imports:
    - jupyterlab_server

about:
  home: http://github.com/jupyterlab/jupyterlab_server
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
