{% set name = "jupyterlab_server" %}
{% set version = "2.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9aec21a2183bbedd9f91a86628355449575f1862d88b28ad5f905019d31e6c21

build:
  number: 0
  # jupyterlab_server isn't available on s390x yet.
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - hatchling
    - setuptools
    - wheel
  run:
    - python
    - babel >=2.10
    - importlib-metadata >=4.8.3  # [py<310]
    - jinja2 >=3.0.3
    - json5 >=0.9.0
    - jsonschema >=4.17.3
    - jupyter_server >=1.21,<3
    - packaging >=21.3
    - requests >=2.28

test:
  requires:
    - pip
  imports:
    - jupyterlab_server
  commands:
    - python -m pip check 
  # downstreams:
    # Additional testing for downstream package jupyterlab
    # 1. Skip s390x and arm64 because nodejs >=14,<15 currently isn't available.
    # 2. Skip ppc64le: npm dependencies failed to install
    #- jupyterlab  # [not (s390x or aarch64 or arm64 or ppc64le)]

about:
  home: https://github.com/jupyterlab/jupyterlab_server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.
  dev_url: https://github.com/jupyterlab/jupyterlab_server
  doc_url: https://jupyterlab-server.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
    - bollwyvl
    - jtpio
