{% set version = "1.0.3" %}

package:
  name: jupyterlab_server
  version: {{ version }}

source:
  fn: jupyterlab_server-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterlab_server/jupyterlab_server-{{ version }}.tar.gz
  sha256: ca78157c75c348bb369dbd17278df0db9679654da5c51c10ee0960912c2990e7

build:
    number: 0
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - json5
    - jsonschema >=3.0.1
    - notebook >=4.2.0

test:
  imports:
    - jupyterlab_server

about:
  home: http://github.com/jupyterlab/jupyterlab_server
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A set of server components for JupyterLab and JupyterLab like applications.

extra:
  recipe-maintainers:
    - jasongrout
    - blink1073
    - afshin
    - SylvainCorlay
